---
- name: set up
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/main.yaml

  roles:
    - dotfiles
    - geerlingguy.dotfiles
    - vscode
    - launchd
    - homebrew
    - homebrew_cask
    - mac_app_store
