- name: Check homebrew upgrade LaunchAgent plist exists
  ansible.builtin.stat:
    path: "{{ lookup('env','HOME') }}/Library/LaunchAgents/local.homebrew.upgrade.plist"
  register: brew_upgrade_plist_stat

- name: Unload homebrew upgrade LaunchAgent
  ansible.builtin.command:
    cmd: launchctl unload {{ lookup('env','HOME') }}/Library/LaunchAgents/local.homebrew.upgrade.plist
  register: brew_upgrade_unload
  when: brew_upgrade_plist_stat.stat.exists
  failed_when:
    - brew_upgrade_unload.rc is defined
    - brew_upgrade_unload.rc != 0
    - "'Could not find specified service' not in (brew_upgrade_unload.stderr | default(''))"
  changed_when: brew_upgrade_unload.rc | default(1) == 0

- name: Remove homebrew upgrade LaunchAgent plist
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/Library/LaunchAgents/local.homebrew.upgrade.plist"
    state: absent
