- name: update homebrew
  community.general.homebrew:
    update_homebrew: true
  ignore_errors: true

- name: upgrade homebrew
  community.general.homebrew:
    upgrade_all: true
  ignore_errors: true

- name: Add fluxcd tap
  community.general.homebrew_tap:
    name: fluxcd/tap

- name: install homebrew packages
  community.general.homebrew:
    name:
      - act
      - argo
      - aqua
      - awscli
      - bat
      - buf
      - cilium-cli
      - colima
      - docker
      - docker-compose
      - eza
      - fluxcd/tap/flux
      - gh
      - git
      - goenv
      - helm
      - helmfile
      - jnv
      - jq
      - k3d
      - k9s
      - kubectl
      - kustomize
      - mas
      - nodenv
      - opentofu
      - peco
      - postgresql # For local development
      - pyenv
      - shellcheck
      - starship
      - tfenv
      - tmux
      - trash-cli
      - rbenv
      - yarn
      - yq
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting

- name: link docker
  command: brew link --overwrite docker
  changed_when: false

- name: link tfenv
  command: brew link --overwrite tfenv
  changed_when: false
